let books = [
    { long_name: 'Gênesis', book_number: 1, short_name: 'gn' },
    { long_name: "Êxodo", book_number: 2, short_name: 'ex' },
    { long_name: "Levítico", book_number: 3, short_name: 'lv' },
    { long_name: "Números", book_number:4, short_name: 'nm' },
    { long_name: "Deuteronômio", book_number: 5, short_name: 'dt' },
    { long_name: "Josué", book_number: 6, short_name: 'js' },
    { long_name: "Juízes", book_number: 7, short_name: 'jz' },
    { long_name: "Rute", book_number: 8, short_name: 'rt' },
    { long_name: "1 Samuel", book_number: 9, short_name: '1sm' },
    { long_name: "2 Samuel", book_number: 10, short_name: '2sm' },
    { long_name: "1 Reis", book_number: 11, short_name: '1rs' },
    { long_name: "2 Reis", book_number: 12, short_name: '2rs' },
    { long_name: "1 Crônicas", book_number: 13, short_name: '1cr' },
    { long_name: "2 Crônicas", book_number: 14, short_name: '2cr' },
    { long_name: "Esdras", book_number: 15, short_name: 'ed' },
    { long_name: "Neemias", book_number: 16, short_name: 'ne' },
    { long_name: "Ester", book_number: 17, short_name: 'et' },
    { long_name: "Jó", book_number: 18, short_name: 'jo' },
    { long_name: "Salmos", book_number: 19, short_name: 'sl' },
    { long_name: "Provérbios", book_number: 20, short_name: 'pv' },
    { long_name: "Eclesiastes", book_number: 21, short_name: 'ec' },
    { long_name: "Cantares", book_number: 22, short_name: 'ct' },
    { long_name: "Isaías", book_number: 23, short_name: 'is' },
    { long_name: "Jeremias", book_number: 24, short_name: 'jr' },
    { long_name: "Lamentações", book_number: 25, short_name: 'lm' },
    { long_name: "Ezequiel", book_number: 26, short_name: 'ez' },
    { long_name: "Daniel", book_number: 27, short_name: 'dn' },
    { long_name: "Oseias", book_number: 28, short_name: 'os' },
    { long_name: "Joel", book_number: 29, short_name: 'jl' },
    { long_name: "Amós", book_number: 30, short_name: 'am' },
    { long_name: "Obadias", book_number: 31, short_name: 'ob' },
    { long_name: "Jonas", book_number: 32, short_name: 'jn' },
    { long_name: "Miqueias", book_number: 33, short_name: 'mq' },
    { long_name: "Naum", book_number: 34, short_name: 'na' },
    { long_name: "Habacuque", book_number: 35, short_name: 'hc' },
    { long_name: "Sofonias", book_number: 36, short_name: 'sf' },
    { long_name: "Ageu", book_number: 37, short_name: 'ag' },
    { long_name: "Zacarias", book_number: 38, short_name: 'zc' },
    { long_name: "Malaquias", book_number: 39, short_name: 'ml' },
    { long_name: 'Mateus', book_number: 40, short_name: 'mt' },
    { long_name: 'Marcos', book_number: 41, short_name: 'mc' },
    { long_name: 'Lucas', book_number: 42, short_name: 'lc' },
    { long_name: 'João', book_number: 43, short_name: 'jo' },
    { long_name: 'Atos dos Apóstolos', book_number: 44, short_name: 'at' },
    { long_name: 'Romanos', book_number: 45, short_name: 'rm' },
    { long_name: '1 Coríntios', book_number: 46, short_name: '1co' },
    { long_name: '2 Coríntios', book_number: 47, short_name: '2co' },
    { long_name: 'Gálatas', book_number: 48, short_name: 'gl' },
    { long_name: 'Efésios', book_number: 49, short_name: 'ef' },
    { long_name: 'Filipenses', book_number: 50, short_name: 'fp' },
    { long_name: 'Colossenses', book_number: 51, short_name: 'cl' },
    { long_name: '1 Tessalonicenses', book_number: 52, short_name: '1ts' },
    { long_name: '2 Tessalonicenses', book_number: 53, short_name: '2ts' },
    { long_name: '1 Timóteo', book_number: 54, short_name: '1tm' },
    { long_name: '2 Timóteo', book_number: 55, short_name: '2tm' },
    { long_name: 'Tito', book_number: 56, short_name: 'tt' },
    { long_name: 'Filemom', book_number: 57, short_name: 'fm' },
    { long_name: 'Hebreus', book_number: 58, short_name: 'hb' },
    { long_name: 'Tiago', book_number: 59, short_name: 'tg' },
    { long_name: '1 Pedro', book_number: 60, short_name: '1pe' },
    { long_name: '2 Pedro', book_number: 61, short_name: '2pe' },
    { long_name: '1 João', book_number: 62, short_name: '1jo' },
    { long_name: '2 João', book_number: 63, short_name: '2jo' },
    { long_name: '3 João', book_number: 64, short_name: '3jo' },
    { long_name: 'Judas', book_number: 65, short_name: 'jd' },
    { long_name: 'Apocalipse', book_number: 66, short_name: 'ap' },
]